---
title: "1000_bulbs_scrape"
author: "Zach Papin"
date: "5/24/2020"
word_document: default
---


```{r setup, include=FALSE}
# Load Necessary libraries (May need to install packages is not already on your comp)
library(tidyverse)  
library(rvest)    
library(stringr)   
library(rebus)     
library(lubridate)
library(selectr)
library(xml2)
library(robotstxt)
library(dplyr)
library(readxl)
library(writexl)
library(ggplot2)


# Clear Environment
rm(list = ls())
```

1. Build a list of all of the webpages that list desired products
```{r chunk 1}
################################################ Categories ################################################ 
## From the website home page, pull all categories that are relavent to GSL

read_html("https://www.1000bulbs.com/category/light-bulbs/") %>% 
  html_nodes(".text-center") %>% 
  html_nodes("a") %>% 
  html_attr("href") -> categories

## Only pull category hyperlinks
categories <- categories[grep("category",categories)]
## Remove unwanted categories
categories <- categories[c(3,7,8,10,12)]
## Append the website tag to the shortened Urls 
categories <- paste("https://www.1000bulbs.com",categories,sep="")


################################################ Sub_categories ################################################ 
## From the Category pages, find which pages end, and which have sub-categories

## Create vector for product pages, and sub categories
product_pages<- c()
sub_categories_pages <- c()

## Loop through categories, if there are hyperlinks on the page that contain further sub_categories append to sub_categories, if not, append to product pages
for(f in 1:length(categories)){
  read_html(categories[f]) %>% 
    html_nodes(".text-center") %>% 
    html_nodes("a") %>% 
    html_attr("href") -> sub_categories
  sub_categories <- sub_categories[grep("category",sub_categories)]
  if(length(sub_categories)<1){product_pages <- append(product_pages,categories[f])}
  if(length(sub_categories)>0){sub_categories_pages <- append(sub_categories_pages,sub_categories)}
}
## Append the website tag to the shortened Urls 
sub_categories_pages<-paste("https://www.1000bulbs.com",sub_categories_pages,sep="")


################################################ Sub_Sub_categories ################################################ 
## From the sub-category pages, find which pages end, and which have further sub-sub-categories

## Create vector for sub-sub-categories
sub_sub_categories_pages <- c()

## Loop through sub-categories, if there are hyperlinks on the page that contain further sub_categories append to sub_sub_categories, if not, append to product pages
for(f in 1:length(sub_categories_pages)){
  read_html(sub_categories_pages[f]) %>% 
    html_nodes(".text-center") %>% 
    html_nodes("a") %>% 
    html_attr("href") -> Sub_sub_categories
  Sub_sub_categories[grep("category",Sub_sub_categories)] -> Sub_sub_categories
  if(length(Sub_sub_categories)<1){product_pages <- append(product_pages,sub_categories_pages[f])}
  if(length(Sub_sub_categories)>0){sub_sub_categories_pages <- append(sub_sub_categories_pages,Sub_sub_categories)}
}
## Append the website tag to the shortened Urls 
sub_sub_categories_pages <- paste("https://www.1000bulbs.com",sub_sub_categories_pages,sep="")


################################################ Sub_Sub_Sub_categories
## From the sub-sub-category pages, find which pages end, and which have further sub-sub-categories

## Create vector for sub-sub-sub-categories
Sub_Sub_Sub_categories_pages <- c()
## Similar loop to above iterations
for(f in 1:length(sub_sub_categories_pages)){
  read_html(sub_sub_categories_pages[f]) %>% 
    html_nodes(".text-center") %>% 
    html_nodes("a") %>% 
    html_attr("href") -> Sub_Sub_Sub_categories
  Sub_Sub_Sub_categories[grep("category",Sub_Sub_Sub_categories)] -> Sub_Sub_Sub_categories
  if(length(Sub_Sub_Sub_categories)<1){product_pages <- append(product_pages,sub_sub_categories_pages[f])}
  if(length(Sub_Sub_Sub_categories)>0){Sub_Sub_Sub_categories_pages <- append(Sub_Sub_Sub_categories_pages,Sub_Sub_Sub_categories)}
}

##### Test if there are any further categories 
# for(f in 1:length(products.2)){
#   read_html(products.2[f]) %>% 
#     html_nodes(".text-center") %>% 
#     html_nodes("a") %>% 
#     html_attr("href") -> x
#   x[grep("category",Sub_Sub_Sub_categories)] -> x
# 
#   if(length(x) > 0){print(f)}
# }

Sub_Sub_Sub_categories_pages <- paste("https://www.1000bulbs.com",Sub_Sub_Sub_categories_pages,sep="")

# Remove Duplicates
product_pages %>% 
  unique() -> product_pages.1

#Filter out unwanted products that to not fit GSL 
product_pages.1 <- product_pages.1[-grep("switch",product_pages.1)]
product_pages.1 <- product_pages.1[-grep("socket",product_pages.1)]
product_pages.1 <- product_pages.1[-grep("silver-bowl",product_pages.1)]
product_pages.1 <- product_pages.1[-grep("accessories",product_pages.1)]
product_pages.1 <- product_pages.1[-grep("lamp-cord",product_pages.1)]
product_pages.1 <- product_pages.1[-grep("lamp-pendants",product_pages.1)]
product_pages.1 <- product_pages.1[-grep("yellow-cfl-bulbs",product_pages.1)]
product_pages.1 <- product_pages.1[-grep("red-cfl-light-bulbs",product_pages.1)]
product_pages.1 <- product_pages.1[-grep("blue-cfl-bulbs",product_pages.1)]

# Append all product pages
products.2 <- append(product_pages.1,Sub_Sub_Sub_categories_pages)

# View Products
head(products.2,10)
```

2. From the product pages, pull the links to the individual units to be scraped
```{r chunk2}


################################################ unit pages
units <- c()
for(f in 1:length(products.2)){
  read_html(products.2[f]) %>% 
    html_nodes(".text-center") %>% 
    html_nodes("a") %>% 
    html_attr("href") -> unit_pages
  unit_pages <-  unit_pages[grep("product", unit_pages)]
  unit_pages <- paste("https://www.1000bulbs.com",unit_pages,sep="")
  units <- append(units,unit_pages)
}

units %>% 
  unique() -> units.1

head(units.1,10) -> units.1
units.1 
```

3. Build a data frame with product specs from unit pages
```{r chunk3}
################################# Product Specs #########################################################


## Create empty dataframe to be populated with product specs
Thousand_Bulbs_Specs <- data.frame(
  Manufacturer= rep(NA, length(units.1)),
  Model_Name	= rep(NA, length(units.1)),
  Model_Number	= rep(NA, length(units.1)),
  Bulb_Shape	= rep(NA, length(units.1)),
  Base_Type	= rep(NA, length(units.1)),
  Technology	= rep(NA, length(units.1)),
  Initial_lumens	= rep(NA, length(units.1)),
  Wattage	= rep(NA, length(units.1)),
  Average_Lifetime = rep(NA, length(units.1)),
  CCT= rep(NA, length(units.1)),
  CRI= rep(NA, length(units.1)),
  Rated_Voltage= rep(NA, length(units.1)),
  Dimmable= rep(NA, length(units.1)),
  Number_of_Bulbs= rep(NA, length(units.1)),
  Beam_Angle	= rep(NA, length(units.1)),
  Nominal_Length	= rep(NA, length(units.1)),
  Diameter= rep(NA, length(units.1)),
  Catalog_Efficacy= rep(NA, length(units.1)),
  Discontinued= rep(NA, length(units.1)),
  Location	= rep(NA, length(units.1)),
  Enclosed_Fixtures	= rep(NA, length(units.1)),
  Application	= rep(NA, length(units.1)),
  link= rep(NA, length(units.1)),
  price= rep(NA, length(units.1))
)

## Loop through units, populating empty data.frame
for(f in 1:length(units.1)){
  read_html("https://www.1000bulbs.com/product/208197/PLT-11232.html") %>% 
    html_nodes("td") %>% 
    html_text %>% 
    str_replace_all( "[\r\n]" , "") %>% 
    trimws(which = c("both", "left", "right"), whitespace = "[ \t\r\n]") -> specs
  
  
  #Manufacturer
  Thousand_Bulbs_Specs$Manufacturer[f] <- specs[match("Brand", specs) +1]
  #Model_Name
  read_html(units.1[f]) %>% 
    html_nodes(".smaller") %>% 
    html_text %>% 
    str_replace_all( "[\r\n]" , "") %>% 
    trimws(which = c("both", "left", "right"), whitespace = "[ \t\r\n]") -> model_name
    Thousand_Bulbs_Specs$Model_Name[f] <- model_name[1]
  #price
  read_html(units.1[f]) %>% 
    html_nodes(".price") %>% 
    html_text %>% 
    str_replace_all( "[\r\n]" , "") %>% 
    trimws(which = c("both", "left", "right"), whitespace = "[ \t\r\n]") -> price
  #Model_Num
  Thousand_Bulbs_Specs$Model_Number[f] <- specs[match("MPN (Part No.)", specs) +1]
  #Bulb_Shape
  Thousand_Bulbs_Specs$Bulb_Shape[f] <- specs[match("Bulb Shape", specs) +1]
  #Base_Type
  Thousand_Bulbs_Specs$Base_Type[f] <- specs[match("Base Type", specs) +1]
  # Technology
  Thousand_Bulbs_Specs$Technology[f] <- "LED"
  # Initial_lumens
  Thousand_Bulbs_Specs$Initial_lumens[f] <- specs[match("Lumens", specs) +1]
  # Wattage
  Thousand_Bulbs_Specs$Wattage[f]<- specs[match("Wattage", specs) +1]
  # Wattage_Equivalency
  Thousand_Bulbs_Specs$Wattage_Equivalency[f]<- specs[match("Incandescent Equal", specs) +1]
  # Retail_Efficiency
  # Average_Lifetime 
  Thousand_Bulbs_Specs$Average_Lifetime[f] <- specs[match("Life Hours", specs) +1]
  # CCT
  Thousand_Bulbs_Specs$CCT[f] <- specs[match("Color Temperature", specs) +1]
  # CRI
  Thousand_Bulbs_Specs$CRI[f] <- specs[match("CRI", specs) +1]
  # Rated_Voltage
  Thousand_Bulbs_Specs$Rated_Voltage[f] <- specs[match("Voltage", specs) +1] 
  # Dimmable
  Thousand_Bulbs_Specs$Dimmable[f] <- specs[match("Dimmable", specs) +1]
  # Number_of_Bulbs
  Thousand_Bulbs_Specs$Number_of_Bulbs[f] <- specs[match("Case Quantity", specs) +1]
  # Beam_Angle
  Thousand_Bulbs_Specs$Beam_Angle[f] <- specs[match("Beam Angle", specs) +1]
  # Nominal_Length
  Thousand_Bulbs_Specs$Nominal_Length[f] <- specs[match("Height", specs) +1]
  # Diameter
  Thousand_Bulbs_Specs$Diameter[f] <- specs[match("Diameter", specs) +1]
  # Catalog_Efficacy
  Thousand_Bulbs_Specs$Catalog_Efficacy[f] <- specs[match("Lumens per Watt", specs) +1]
  # Discontinued
  # Location
  Thousand_Bulbs_Specs$Location[f] <- specs[match("Safety Rating", specs) +1]
  # Enclosed_Fixtures
  Thousand_Bulbs_Specs$Enclosed_Fixtures[f] <- specs[match("Enclosed Fixture Rated", specs) +1]
  # Application
  Thousand_Bulbs_Specs$Application[f] <- specs[match("Operation", specs) +1]
  # link
  Thousand_Bulbs_Specs$link[f] <- units.1[f]
  # Price
    read_html(units.1[f]) %>% 
    html_nodes(".price") %>% 
    html_text %>% 
    str_replace_all( "[\r\n]" , "") %>% 
    trimws(which = c("both", "left", "right"), whitespace = "[ \t\r\n]") -> price
    Thousand_Bulbs_Specs$price[f] <- price[1] 
  
}

Thousand_Bulbs_Specs


#write_csv(Thousand_Bulbs_Specs, "//chi1islfls02/wdc1fls01_eepa-ams/Lighting/Master Lamp Databases/2020 Lamps Databases/Web Scrape/1000 Bulbs/Thousand_Bulbs_Specs_2_test.csv")

```